services:
    opensearch:
        image: opensearchproject/opensearch:latest
        container_name: opensearch
        environment:
            - "discovery.type=single-node"
            - "plugins.security.disabled=true"
            - "OPENSEARCH_INITIAL_ADMIN_PASSWORD=*AaXkNHw2kmzY"
        ulimits:
            memlock:
                soft: -1
                hard: -1
        volumes:
            - opensearch-data:/usr/share/opensearch/data
        ports:
            - "9200:9200"
            - "9600:9600"
        healthcheck:
            test: ["CMD-SHELL", "curl -f http://localhost:9200 || exit 1"]
            interval: 30s
            timeout: 10s
            retries: 5

    jaeger:
        image: jaegertracing/all-in-one:latest
        container_name: jaeger
        environment:
            - SPAN_STORAGE_TYPE=elasticsearch
            - ES_SERVER_URLS=http://opensearch:9200
            - ES_USERNAME=admin
            - ES_PASSWORD=*AaXkNHw2kmzY
        depends_on:
            opensearch:
                condition: service_healthy
        ports:
            - "8081:16686" # Jaeger UI
            - "14268"
            - "14250"

    otel-collector:
        image: otel/opentelemetry-collector-contrib:latest
        container_name: otel-collector
        command: ["--config=/etc/otel-collector-config.yml"]
        user: "0:0"
        volumes:
            - ./otel-collector-config.yml:/etc/otel-collector-config.yml
            - ./tmp/otelcol-data:/tmp/otelcol
        ports:
            - "1888:1888" # pprof extension
            - "13133:13133" # health_check extension
            - "4317:4317" # OTLP gRPC receiver
            - "4318:4318" # http gRPC receiver
            - "55679:55679" # zpages extension
        depends_on:
            - jaeger
        links:
            - jaeger

volumes:
    opensearch-data:
    otelcol-data:
